# Generated by Django 6.1 on 2026-08-16 05:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateField(auto_created=True, auto_now_add=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "body_part",
                    models.CharField(
                        choices=[
                            ("CHEST", "Chest"),
                            ("BACK", "Back"),
                            ("ARMS", "Arms"),
                            ("LEGS", "Legs"),
                            ("SHOULDERS", "Shoulders"),
                            ("CORE", "Core"),
                            ("NECK", "Neck"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "primary_muscle",
                    models.CharField(
                        choices=[
                            ("CHEST", "Chest"),
                            ("LATS", "Lats"),
                            ("MIDDLE_BACK", "Middle Back"),
                            ("LOWER_BACK", "Lower Back"),
                            ("TRAPS", "Traps"),
                            ("BICEPS", "Biceps"),
                            ("TRICEPS", "Triceps"),
                            ("FOREARMS", "Forearms"),
                            ("QUADRICEPS", "Quadriceps"),
                            ("HAMSTRINGS", "Hamstrings"),
                            ("GLUTES", "Glutes"),
                            ("CALVES", "Calves"),
                            ("ABDUCTORS", "Abductors"),
                            ("ADDUCTORS", "Adductors"),
                            ("SHOULDERS", "Shoulders"),
                            ("ABDOMINALS", "Abdominals"),
                            ("NECK", "Neck"),
                        ],
                        max_length=100,
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                ("archive", models.BooleanField(blank=True, default=False, null=True)),
                ("last_modified", models.DateField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_updater",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalExercise",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "date_created",
                    models.DateField(auto_created=True, blank=True, editable=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "body_part",
                    models.CharField(
                        choices=[
                            ("CHEST", "Chest"),
                            ("BACK", "Back"),
                            ("ARMS", "Arms"),
                            ("LEGS", "Legs"),
                            ("SHOULDERS", "Shoulders"),
                            ("CORE", "Core"),
                            ("NECK", "Neck"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "primary_muscle",
                    models.CharField(
                        choices=[
                            ("CHEST", "Chest"),
                            ("LATS", "Lats"),
                            ("MIDDLE_BACK", "Middle Back"),
                            ("LOWER_BACK", "Lower Back"),
                            ("TRAPS", "Traps"),
                            ("BICEPS", "Biceps"),
                            ("TRICEPS", "Triceps"),
                            ("FOREARMS", "Forearms"),
                            ("QUADRICEPS", "Quadriceps"),
                            ("HAMSTRINGS", "Hamstrings"),
                            ("GLUTES", "Glutes"),
                            ("CALVES", "Calves"),
                            ("ABDUCTORS", "Abductors"),
                            ("ADDUCTORS", "Adductors"),
                            ("SHOULDERS", "Shoulders"),
                            ("ABDOMINALS", "Abdominals"),
                            ("NECK", "Neck"),
                        ],
                        max_length=100,
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                ("archive", models.BooleanField(blank=True, default=False, null=True)),
                ("last_modified", models.DateField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="categories.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical exercise",
                "verbose_name_plural": "historical exercises",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
